# Generated by Django 5.1.4 on 2025-01-07 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('test_case', models.TextField()),
                ('answer_template', models.TextField()),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questiongroup')),
            ],
        ),
    ]
