# Generated by Django 5.1.4 on 2025-01-07 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('questions', '0002_alter_question_answer_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.languages'),
        ),
    ]
