# Generated by Django 5.1.4 on 2025-01-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='test_status',
            field=models.BooleanField(default=False),
        ),
    ]
